### PR TITLE
Remove body parser

### PR DESCRIPTION
**Pull request by ruimarinho**

### CODE REVIEW

**Comment by ruimarinho** [comment]
@thomseddon done. I've added one new commit which replaces thunks by `thenify`, since support for thunks will be removed in `co` in the future. Sound good?

**Comment by thomseddon** [comment]
Yup, I think it probably makes sense to switch to promises
This look amazing now, definitely a v1 we can be proud of, massive simplification!

The only thing left would be the version bump & changelog

**Comment by ruimarinho** [comment]
Alright, merging and preparing v1!

**Comment by ruimarinho** [comment]
@thomseddon done. Would like to have the honour to publish it on npm :)?

**Comment by thomseddon** [comment]
Done, thanks a lot: https://www.npmjs.com/package/koa-oauth-server

**Pull request merged**
